version: "3.7"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: currency-exchange-api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_PREFIX=currency-exchange-development-
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - ./server/node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    command: npm run start
    depends_on:
      - redis

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: currency-exchange-frontend
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - api

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
